### ISSUE TITLE
Need Help Getting The Script To Run

### ISSUE THREAD

**Issue by Jib128** [skalidindi/yosemite-reservations#1]
Hi. I really appreciate you taking the time to make this script. I have a few questions:

1. How do I use the "days-to-include" part? 

`python campsites.py --start_date 2021-07-15 --end_date 2021-07-19 --days-to-include 16,17,18`

Does this mean the script will only look for campsites that are open on the 16th, 17th, AND 18th? Or will it look at the days separately. Or is that the number of consecutive days it will look for?

2. When I input the line above, it spits out this:

`Traceback (most recent call last):
  File "C:\Users\yyzji\Downloads\yosemite-reservations\campsites.py", line 145, in <module>
    CAMPSITES = get_available_campsites(
  File "C:\Users\yyzji\Downloads\yosemite-reservations\campsites.py", line 36, in get_available_campsites
    for _, campsite_details in campground_availabilities["campsites"].items():
KeyError: 'campsites'`

How can I fix this?

Just FYI, I'm on the latest version of python, I pip installed all the requirements, I filled out my gmail in the .ini file, and commented out line 155 and line 157 (twilio and .csv).

**Comment by paniwani** [comment]
Same issue here

**Comment by skalidindi** [comment]
Sorry I completely missed this issue. I rewrote the codebase to run on NodeJS & AWS Lambda. Feel free to give that a try.

Also, to answer your question "DAYS_TO_INCLUDE" allows a user to pick which days of the week you want. It is a comma delimited list of numbers ranging from 0-6 where 0 is Sunday and 1 is Monday and so on.

For example: 5,6 would tell the program to only select Fridays and Saturdays as candidates.
